name: Deploy to EC2

on:
  # kick off deploy after either pipeline finishes
  workflow_run:
    workflows: [ "Backend CI (Maven + ECR)", "Frontend & Nginx CI" ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 98.88.25.18
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}          # paste PEM contents into this secret
          script: |
            set -e
            cd /home/ubuntu/bookportal

            # ECR login (instance should have IAM role with ECR pull; otherwise add AWS keys)
            aws ecr get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin 254518245611.dkr.ecr.us-east-1.amazonaws.com

            # Pull latest images & restart
            (docker compose pull || docker-compose pull)
            (docker compose up -d || docker-compose up -d)
